server:
  port: 8081
  servlet:
    context-path: /app

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/webmarket-app
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    properties:
      hibernate:
        format-sql: true